//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpBoot {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ISODesc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ISODesc() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpBoot.ISODesc", typeof(ISODesc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CHNTPW is a utility to reset the password of any user that has a valid local account on your Windows system..
        /// </summary>
        internal static string chntpw {
            get {
                return ResourceManager.GetString("chntpw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clonezilla is a partition and disk imaging/cloning program similar to True Image® or Norton Ghost®..
        /// </summary>
        internal static string clonezilla {
            get {
                return ResourceManager.GetString("clonezilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DBAN is a self-contained boot disk that automatically deletes the contents of any disk it detects..
        /// </summary>
        internal static string dban {
            get {
                return ResourceManager.GetString("dban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edubuntu is the Education version of Ubuntu..
        /// </summary>
        internal static string edubuntu {
            get {
                return ResourceManager.GetString("edubuntu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fedora is a fast, stable, and powerful operating system for everyday use built by a worldwide community of friends..
        /// </summary>
        internal static string fedora {
            get {
                return ResourceManager.GetString("fedora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fusion Linux is a Linux distribution that has desktop usability..
        /// </summary>
        internal static string fusionlinux {
            get {
                return ResourceManager.GetString("fusionlinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GParted is a free partition manager that enables you to resize, copy, and move partitions without data loss..
        /// </summary>
        internal static string gparted {
            get {
                return ResourceManager.GetString("gparted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inquisitor is an open-source hardware testing and certification system..
        /// </summary>
        internal static string inquisitor {
            get {
                return ResourceManager.GetString("inquisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kali Linux is a penetration testing Linux distribution..
        /// </summary>
        internal static string kalilinux {
            get {
                return ResourceManager.GetString("kalilinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Knoppix is a Debian-based Linux distribution..
        /// </summary>
        internal static string knoppix {
            get {
                return ResourceManager.GetString("knoppix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kubuntu is the KDE version of Ubuntu..
        /// </summary>
        internal static string kubuntu {
            get {
                return ResourceManager.GetString("kubuntu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lubuntu is the LXDE version of Ubuntu..
        /// </summary>
        internal static string lubuntu {
            get {
                return ResourceManager.GetString("lubuntu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Memtest86 is an open source memory test software programs designed to test and stress test an x86 architecture computer&apos;s RAM..
        /// </summary>
        internal static string memtest86 {
            get {
                return ResourceManager.GetString("memtest86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NetbootCD is a Linux live CD based on Tiny Core Linux..
        /// </summary>
        internal static string netbootcd {
            get {
                return ResourceManager.GetString("netbootcd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ophcrack is a free Windows password cracker based on rainbow tables..
        /// </summary>
        internal static string ophcrack {
            get {
                return ResourceManager.GetString("ophcrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Redo Backup is an easy rescue system with GUI tools for full system backup, bare metal recovery and partition editing..
        /// </summary>
        internal static string redobackup {
            get {
                return ResourceManager.GetString("redobackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UBCD 4 DOS is a system that regroups lots of useful utilities..
        /// </summary>
        internal static string ubcd4dos {
            get {
                return ResourceManager.GetString("ubcd4dos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ubuntu is a fast, free and incredibly easy to use Linux distribution..
        /// </summary>
        internal static string ubuntu {
            get {
                return ResourceManager.GetString("ubuntu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ubuntu GNOME is the GNOME edition of Ubuntu..
        /// </summary>
        internal static string ubuntugnome {
            get {
                return ResourceManager.GetString("ubuntugnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ubuntu Server is the server edition of the popular Linux distribution, Ubuntu..
        /// </summary>
        internal static string ubuntuserver {
            get {
                return ResourceManager.GetString("ubuntuserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ubuntu Studio is a free and open operating system for creative people..
        /// </summary>
        internal static string ubuntustudio {
            get {
                return ResourceManager.GetString("ubuntustudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Xubuntu is the Xfce version of Ubuntu..
        /// </summary>
        internal static string xubuntu {
            get {
                return ResourceManager.GetString("xubuntu", resourceCulture);
            }
        }
    }
}
