//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpBoot {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpBoot.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boot from first hard drive.
        /// </summary>
        internal static string BootFromHDD {
            get {
                return ResourceManager.GetString("BootFromHDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has successfully been installed to drive {1}..
        /// </summary>
        internal static string BootloaderInstalled {
            get {
                return ResourceManager.GetString("BootloaderInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calculated in.
        /// </summary>
        internal static string CalcIn {
            get {
                return ResourceManager.GetString("CalcIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changes will take effect after restarting the application..
        /// </summary>
        internal static string ChangesNeedRestart {
            get {
                return ResourceManager.GetString("ChangesNeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} checksum of.
        /// </summary>
        internal static string ChkOf {
            get {
                return ResourceManager.GetString("ChkOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copying.
        /// </summary>
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copying ISO files....
        /// </summary>
        internal static string CopyISOfiles {
            get {
                return ResourceManager.GetString("CopyISOfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not detect which operating system is in this disc image..
        /// </summary>
        internal static string CouldntDetect {
            get {
                return ResourceManager.GetString("CouldntDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creating ISO file....
        /// </summary>
        internal static string CreatingISO {
            get {
                return ResourceManager.GetString("CreatingISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creating multiboot USB key....
        /// </summary>
        internal static string CreatingUSB {
            get {
                return ResourceManager.GetString("CreatingUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detected:.
        /// </summary>
        internal static string Detected {
            get {
                return ResourceManager.GetString("Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download complete..
        /// </summary>
        internal static string DownComplete {
            get {
                return ResourceManager.GetString("DownComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extracting base disk....
        /// </summary>
        internal static string ExtractBaseDisk {
            get {
                return ResourceManager.GetString("ExtractBaseDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extracting ImageMagick....
        /// </summary>
        internal static string ExtractImageMagick {
            get {
                return ResourceManager.GetString("ExtractImageMagick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extracting Mkisofs....
        /// </summary>
        internal static string ExtractMkisofs {
            get {
                return ResourceManager.GetString("ExtractMkisofs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à B.
        /// </summary>
        internal static string FileUnit {
            get {
                return ResourceManager.GetString("FileUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Undetermined error while formatting..
        /// </summary>
        internal static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formatting.
        /// </summary>
        internal static string Formatting {
            get {
                return ResourceManager.GetString("Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start the formatting operation?\nThis will DESTROY any data on the target!.
        /// </summary>
        internal static string FormatWillErase {
            get {
                return ResourceManager.GetString("FormatWillErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generating main menu....
        /// </summary>
        internal static string GenMainMenu {
            get {
                return ResourceManager.GetString("GenMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generating menu.
        /// </summary>
        internal static string GenMenu {
            get {
                return ResourceManager.GetString("GenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generating menus....
        /// </summary>
        internal static string GenMenus {
            get {
                return ResourceManager.GetString("GenMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hard drive.
        /// </summary>
        internal static string HDD {
            get {
                return ResourceManager.GetString("HDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initializing....
        /// </summary>
        internal static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installing {0} on {1}....
        /// </summary>
        internal static string InstallingBoot {
            get {
                return ResourceManager.GetString("InstallingBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The iso file has been successfully created.\nWould you like to try it on QEMU?.
        /// </summary>
        internal static string IsoCreated {
            get {
                return ResourceManager.GetString("IsoCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISO created.
        /// </summary>
        internal static string IsoCreatedTitle {
            get {
                return ResourceManager.GetString("IsoCreatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISO image.
        /// </summary>
        internal static string ISOImg {
            get {
                return ResourceManager.GetString("ISOImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must have administrator rights to format the USB key..
        /// </summary>
        internal static string NeedAdmin {
            get {
                return ResourceManager.GetString("NeedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The selected partition is too big for {0}.
        /// </summary>
        internal static string PartitionTooBig {
            get {
                return ResourceManager.GetString("PartitionTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pictures.
        /// </summary>
        internal static string PicFilter {
            get {
                return ResourceManager.GetString("PicFilter", resourceCulture);
            }
        }
    }
}
