//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpBoot {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpBoot.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About SharpBoot.
        /// </summary>
        internal static string AboutSharpBoot {
            get {
                return ResourceManager.GetString("AboutSharpBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Custom Entry.
        /// </summary>
        internal static string AddCustomEntry {
            get {
                return ResourceManager.GetString("AddCustomEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add files.
        /// </summary>
        internal static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boot from first hard drive.
        /// </summary>
        internal static string BootFromHDD {
            get {
                return ResourceManager.GetString("BootFromHDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has successfully been installed to drive {1}..
        /// </summary>
        internal static string BootloaderInstalled {
            get {
                return ResourceManager.GetString("BootloaderInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calculated in {0}.
        /// </summary>
        internal static string CalcIn {
            get {
                return ResourceManager.GetString("CalcIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changes will take effect after restarting the application..
        /// </summary>
        internal static string ChangesNeedRestart {
            get {
                return ResourceManager.GetString("ChangesNeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} checksum of {1}:.
        /// </summary>
        internal static string ChkOf {
            get {
                return ResourceManager.GetString("ChkOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the bootloader you want to install:.
        /// </summary>
        internal static string ChooseBootloader {
            get {
                return ResourceManager.GetString("ChooseBootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copying {0}.
        /// </summary>
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copying ISO files....
        /// </summary>
        internal static string CopyISOfiles {
            get {
                return ResourceManager.GetString("CopyISOfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not detect which operating system is in this disc image..
        /// </summary>
        internal static string CouldntDetect {
            get {
                return ResourceManager.GetString("CouldntDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create multiboot USB key.
        /// </summary>
        internal static string CreateMultibootUsb {
            get {
                return ResourceManager.GetString("CreateMultibootUsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creating ISO file....
        /// </summary>
        internal static string CreatingISO {
            get {
                return ResourceManager.GetString("CreatingISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creating multiboot USB key....
        /// </summary>
        internal static string CreatingUSB {
            get {
                return ResourceManager.GetString("CreatingUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download complete..
        /// </summary>
        internal static string DownComplete {
            get {
                return ResourceManager.GetString("DownComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extracting base disk....
        /// </summary>
        internal static string ExtractBaseDisk {
            get {
                return ResourceManager.GetString("ExtractBaseDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extracting {0}....
        /// </summary>
        internal static string Extracting {
            get {
                return ResourceManager.GetString("Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File already exists..
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File system:.
        /// </summary>
        internal static string Filesystem {
            get {
                return ResourceManager.GetString("Filesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à B.
        /// </summary>
        internal static string FileUnit {
            get {
                return ResourceManager.GetString("FileUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Undetermined error while formatting..
        /// </summary>
        internal static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formatting.
        /// </summary>
        internal static string Formatting {
            get {
                return ResourceManager.GetString("Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start the formatting operation?\nThis will DESTROY any data on the target!.
        /// </summary>
        internal static string FormatWillErase {
            get {
                return ResourceManager.GetString("FormatWillErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generating main menu....
        /// </summary>
        internal static string GenMainMenu {
            get {
                return ResourceManager.GetString("GenMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generating menu {0}.
        /// </summary>
        internal static string GenMenu {
            get {
                return ResourceManager.GetString("GenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generating menus....
        /// </summary>
        internal static string GenMenus {
            get {
                return ResourceManager.GetString("GenMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initializing....
        /// </summary>
        internal static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install a bootloader on a USB key.
        /// </summary>
        internal static string InstallABootLoader {
            get {
                return ResourceManager.GetString("InstallABootLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installing {0} on {1}....
        /// </summary>
        internal static string InstallingBoot {
            get {
                return ResourceManager.GetString("InstallingBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The ISO file has been successfully created.\nWould you like to try it on QEMU?.
        /// </summary>
        internal static string IsoCreated {
            get {
                return ResourceManager.GetString("IsoCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISO created.
        /// </summary>
        internal static string IsoCreatedTitle {
            get {
                return ResourceManager.GetString("IsoCreatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ISO image.
        /// </summary>
        internal static string ISOImg {
            get {
                return ResourceManager.GetString("ISOImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must have administrator rights to format the USB key..
        /// </summary>
        internal static string NeedAdmin {
            get {
                return ResourceManager.GetString("NeedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation cancelled.
        /// </summary>
        internal static string OpCancelled {
            get {
                return ResourceManager.GetString("OpCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The selected partition is too big for {0}.
        /// </summary>
        internal static string PartitionTooBig {
            get {
                return ResourceManager.GetString("PartitionTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pictures.
        /// </summary>
        internal static string PicFilter {
            get {
                return ResourceManager.GetString("PicFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (recommended).
        /// </summary>
        internal static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remaining time: {0:hh\:mm\:ss}.
        /// </summary>
        internal static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SharpBoot uses the following software:.
        /// </summary>
        internal static string SharpBootUsesSoft {
            get {
                return ResourceManager.GetString("SharpBootUsesSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ,K,M,G,T,P,E,Z,Y.
        /// </summary>
        internal static string SizeSuffixes {
            get {
                return ResourceManager.GetString("SizeSuffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Volume label:.
        /// </summary>
        internal static string VolumeLabel {
            get {
                return ResourceManager.GetString("VolumeLabel", resourceCulture);
            }
        }
    }
}
